export const LOAD_UNITS_START = "LOAD_UNITS_START";
export const LOAD_UNITS_SUCCESS = "LOAD_UNITS_SUCCESS";
export const LOAD_UNITS_ERROR = "LOAD_UNITS_ERROR";


 /* export const FILTER_BY_AGE_START = "FILTER_BY_AGE_START";
export const FILTER_BY_AGE_SUCCESS = "FILTER_BY_AGE_SUCCESS";
export const FILTER_BY_AGE_ERROR = "FILTER_BY_AGE_ERROR";

export const FILTER_BY_COST_START = "FILTER_BY_COST_START";
export const FILTER_BY_COST_SUCCESS = "FILTER_BY_COST_SUCCESS";
export const FILTER_BY_COST_ERROR = "FILTER_BY_COST_ERROR";  */ 

export const FILTER_START = "FILTER_START";
export const FILTER_SUCCESS = "FILTER_SUCCESS";
export const FILTER_ERROR = "FILTER_ERROR";


